server:
  port: 9090
file:
  upload-dir: ./upload
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/code?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  web:
    resources:
      static-locations: file:${file.upload-dir}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
      location: ./upload/
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  #MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true